# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/vyshnavi2001/NNDL/blob/main/ASSIGMENT1.ipynb
"""

from sympy import *
x=symbols('x')
F=x*4+3*x*2+10
y=diff(F,x) 
print(y)
X=int(input("enter x value:"))
iteration=1 
n=0.1 
epoch=2
while (iteration >= epoch) :
   Y=y.subs(x,X)
   deltax=-n*Y
   newx = X + deltax
   iteration= iteration + 1
   X=newx
print("final x =",X)
print("Minimum value of f(x)",F.subs(x,X))